platform :ios, '12.0'

# Load React Native scripts
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Resolve React Native dependencies
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p', "require.resolve('#{script}', {paths: ['#{Pod::Config.instance.installation_root}/..']})"]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('@react-native-community/cli-platform-ios/native_modules.rb')

# Specify the Xcode project
project 'reactNativeItsNotification.xcodeproj'

target 'reactNativeItsNotification' do
#   config = use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => false
  )

  # Firebase pods compatible with version 20.3.0
  pod 'Firebase', '~> 10.0'
  pod 'Firebase/Messaging'

  # React Native Firebase native modules
  pod 'RNFirebase', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFirebaseMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  target 'reactNativeItsNotificationTests' do
    inherit! :complete
    # Pods for testing
  end

  use_frameworks! :linkage => :static

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
    end
  end
end